---
title: "weight M explanation"
author: "John Stansfield"
date: "September 17, 2017"
output: html_document
---

# Weighting of M values by Average expression

M values are defined as $log2(IF2 / IF1)$. Since M values are the result of a ratio, differences on the log scale can appear identical when on the raw scale they are actually very different. For instance The M values for IF1 = 1 and IF2 = 10 and for IF1 = 10 and IF2 = 100 are both 3.32, despite the fact that the second pair of interaction frequencies has a much larger difference on the raw scale. This could potentially lead to issues in the analysis of Hi-C data, as IFs with lower average expression values are less trustworthy and more prone to display differences due solely to chance or technical biases rather than true biological differences. Therefore, M values derived from IFs with large average expression should be treated as more trustworthy than those derived from IFs exhibitng small average expression. One solution to this issue to weight M values based on their corresponding average expression before performing difference detection. 

To weight M values, first we calculate the average expression associated with each M value, $A = (IF1 + IF2) / 2$. Simple plotting of A values indicates that average expression between two Hi-C datasets is roughly distributed in a powerlaw fashion, with the majority of A values being rather small and a long right tail of very large A values. A values less than 1 should not be trusted at all and so they can safely be ignored for now. Based on the data we will need to determine a minimum A value at which to start weighting. All values less than this $A_{min}$ value will be weighted to 0. If we take the values of A greater than $A_{min}$ and less than the 75th quantile we get a more reasonable distribution of values to work with. A values over the 75th quantile can safely be assumed to be trusted as they are very large compared to the rest. We choose to only calculate weights for this center of the A distribution. We estimate the kernel density for the A values which fall into the range $A > A_{min} and A < A_{0.75}$. The approximate probability density function, $f_A(.)$, of the kernel density is then interpolated from the kernel density. Next, we fit a powerlaw to this subset of A. The powerlaw is defined as $P(A) = cA^{-\alpha}$. We get the best fit of the powerlaw to the kernel density by minimizing the sum of squared residuals (SSR) between the powerlaw fit and the kernel density. The weights, $w$, can be calculated as follows
$$w = \begin{cases} 0, \  A < A_{min} \\
1 - \frac{P(A)}{max(P(A))}, \ A_{min} \le A < A_{0.75} \\
1, \ A \ge A_{0.75}
\end{cases}
$$
where $P(A)$ is the powerlaw fit based on the minimizing the SSR. This weighting scheme will produce weights on [0, 1] corresponding the powerlaw fit to the estimated kernel density of A. The weights can then be multiplied to the normalized M values before difference detection is performed. The weights can only make the M values closer to 0 and thus the differences represented will become less significant if their corresponding A value is low. M values corresponding to high A values will be unchanged. 
