---
title: "Untitled"
author: "John Stansfield"
date: "September 13, 2017"
output: html_document
---

# test p-value adjustment

```{r}
# power-law function
.powerlaw <- function(x, C, alpha) {
  C * x^(-alpha)
}
```


```{r}
library(HiCcompare)

data('HMEC.chr22')
data('NHEK.chr22')
hic.table <- create.hic.table(HMEC.chr22, NHEK.chr22, chr = 'chr22')
# Plug hic.table into hic_loess()
result <- hic_loess(hic.table, Plot = TRUE)
# perform difference detection
diff.result <- hic_diff(result, diff.thresh = 'auto', Plot = TRUE)

hic.table <- diff.result

######
library(poweRlaw)
# calculate A
hic.table[, A := (adj.IF1 + adj.IF2) / 2]
fit <- conlnorm$new(hic.table$A)
# fit$setXmin(1)
est <- estimate_xmin(fit)
fit$setXmin(est)
est <- estimate_pars(fit)
fit$setPars(est)


fit <- conlnorm$new(hic.table$A)
est <- estimate_xmin(fit)
fit$setXmin(est)
est <- estimate_pars(fit)
fit$setPars(est)
plot(fit)
lines(fit, col=2)

fit2 <- conpl$new(hic.table$A)
est <- estimate_xmin(hic.table$A)
fit2$setXmin(est)
est <- estimate_pars(hic.table$A)
fit2$setPars(est)
plot(fit2)
lines(fit2, col=2)

# test if powerlaw fit is good using KS
# bs_p <- bootstrap_p(fit, no_of_sims = 10, threads = 1)


# library(fitdistrplus)
library(igraph)
fit_power_law(hic.table$A)
length(hic.table$A[hic.table$A < 4000])
fit_power_law(hic.table$A[hic.table$A < 4000])

# fit power law by deleting most extreme values
fit_powerlaw = function(x) {
  x = na.omit(x) # remove any NAs
  fit = power.law.fit(x) # get initial fit
  pval = fit$KS.p
  # loop until fit is good
  while(pval <= 0.05) {
    x = x[-which(x == max(x))]
    fit = power.law.fit(x)
    pval = fit$KS.p
  }
  return(fit)
}


fit <- fit_powerlaw(hic.table$A)

 .powerlaw(hic.table$A, fit$xmin, fit$alpha)


.powerlaw(7, fit$xmin, fit$alpha)
# between 6 and 7 the powerlaw fit hits 1. values > 7 are below 1 and and x increases to inf the value returned goes to 0

# test multiplying powerlaw result by p-value
adj.p <- hic.table$p.value * (1 + .powerlaw(hic.table$A, fit$xmin, fit$alpha))
hist(adj.p)

plaw <- .powerlaw(hic.table$A, fit$xmin, fit$alpha)
hist(plaw)

cbind(hic.table$A, hic.table$p.value, adj.p)[1:100,]
cbind(hic.table$A, hic.table$p.value, adj.p)[2000:2100,]

MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p)
MD.plot2(hic.table$adj.M, hic.table$D, adj.p)
# that isn't going to work. Makes pretty much everything super significant

# could we weight fold changes based on average expression before performing permutation test instead?
# find midpoint of log A, this corresponds to weight of 1. A < midpoint downweight M and A > midpoint upweight M??


# maybe find change point on log A centered bell curve then use that as the multiplier. Things on tails either thrown 
# out for left tail or multiplied by 1 for right tail


# try weighting by raw difference
hic.table <- diff.result
weight <- (abs(hic.table$adj.IF1 - hic.table$adj.IF2) / max(c(hic.table$adj.IF1, hic.table$adj.IF2)))

hic.table[, weight := weight]
hic.table[, adj.p := p.value * weight]
hic.table
```

# Test function on different datasets

## set up prostate data
```{r}
library(GenomicRanges)
core_path <- "D:/3D_DNA/rickman/rickman_lib1/"
man_path <- "D:/3D_DNA/manuscript/prostate_analysis/"

chrs <- paste0('chr', 1:22)
chrs <- c(chrs, 'chrX')

# read in data for 1 mb
ERG_lib1 <- list()
GFP_lib1 <- list()
for(i in 1:22) {
  ERG_lib1[[i]] <- read.table(paste0(core_path, 'ERG_lib1_chr', i, '.1mb.txt'), header = FALSE)
  GFP_lib1[[i]] <- read.table(paste0(core_path, 'GFP_lib1_chr', i, '.1mb.txt'), header = FALSE)
}
ERG_lib1[[23]] <- read.table(paste0(core_path, 'ERG_lib1_chr', 'X', '.1mb.txt'), header = FALSE)
GFP_lib1[[23]] <- read.table(paste0(core_path, 'GFP_lib1_chr', 'X', '.1mb.txt'), header = FALSE)

cnv <- read.table('D:/3D_DNA/rickman/cnv_out.bed', header = TRUE)

# cnv_rows <- which(cnv$ERG_lib1_1_2.hicup == -2 | cnv$ERG_lib1_1_2.hicup == 2 | cnv$GFP_lib1_1_2.hicup == -2 | cnv$GFP_lib1_1_2.hicup == 2)
# exclude <- cnv[cnv_rows, 2:4]
# cnv <- cnv[cnv_rows,]
cnv.gi <- GRanges(seqnames = cnv$chromosome, ranges = IRanges(start = cnv$start, end = cnv$end))
colnames(cnv)[1] <- 'chr'
exclude <- rbind(cnv, hg19_blacklist)
#exclude <- hg19_blacklist
exclude.gi <- GRanges(seqnames = exclude$chr, ranges = IRanges(start = exclude$start, end = exclude$end))

lib1_tables <- mapply(create.hic.table, ERG_lib1, GFP_lib1, chrs, SIMPLIFY = FALSE, MoreArgs = list(scale = FALSE, include.zeros = FALSE,
                                                                                                    exclude.regions = exclude, 
                                                                                                    exclude.overlap = 0.2))


lib1_tables <- total_sum(lib1_tables)


lib1_tables <- hic_loess(lib1_tables, Plot = TRUE, span = NA)
lib1_tables <- hic_diff(lib1_tables, Plot = TRUE, diff.thresh = NA, iterations = 1000)


```

## test p-value adjustment

### chr22 test data
```{r}
data('HMEC.chr22')
data('NHEK.chr22')
hic.table <- create.hic.table(HMEC.chr22, NHEK.chr22, chr = 'chr22')
# Plug hic.table into hic_loess()
result <- hic_loess(hic.table, Plot = TRUE)
# perform difference detection
diff.result <- hic_diff(result, diff.thresh = 'auto', Plot = TRUE)

hic.table <- diff.result

adjust_pval(hic.table)
```

### prostate data
```{r}
chr1 <- lib1_tables[[1]]
chr1 <- adjust_pval(chr1)

par(mfrow = c(1,2))
MD.plot2(chr1$M, chr1$D, chr1$p.value)
MD.plot2(chr1$M, chr1$D, chr1$adj.p)

# Powerlaw Xmin = 7.29600338922691 Powerlaw alpha = 84.4788481904521
```

