---
title: "kal_multi_res"
author: "John Stansfield"
date: "December 19, 2017"
output:
  pdf_document: default
  html_document: default
---




```{r, message=F, warning=F}
library(readr)
library(data.table)
library(HiCcompare)
library(dplyr)
library(pROC)
```

# 10KB

```{r, message = FALSE, warning=FALSE, results='hide', cache=FALSE, echo = FALSE}
# Set up
#####
centromeres <- read.table("D:/brain/data/hg38_centromeres.bed")

# for dplfc 1 (dplfc folder)
dplfc_1_mat <- read_tsv("D:/brain/data/all_resolutions/dplfc_10000.matrix", col_names = FALSE) %>% as.data.table()
dplfc_1_bed <- read_tsv("D:/brain/data/all_resolutions/dplfc_10000_abs.bed", col_names = FALSE) %>% as.data.table()

# for dplfc 2 (dplfc folder)
dplfc_2_mat <- read_tsv("D:/brain/data/all_resolutions/dplfc_upseq_10000.matrix", col_names = FALSE) %>% as.data.table()
dplfc_2_bed <- read_tsv("D:/brain/data/all_resolutions/dplfc_upseq_10000_abs.bed", col_names = FALSE) %>% as.data.table()


dplfc_1 <- hicpro2bedpe(dplfc_1_mat, dplfc_1_bed)$cis[-c(23,25)] # remove chrM and chrY
dplfc_2 <- hicpro2bedpe(dplfc_2_mat, dplfc_1_bed)$cis[-c(23,25)] # remove chrM and chrY

dplfc1_2 <- mapply(create.hic.table, dplfc_1[1], dplfc_2[1], MoreArgs = list(exclude.regions = centromeres, exclude.overlap = 0,
                                                                       scale = TRUE), SIMPLIFY = FALSE)

```

## adjusted p-values
```{r, warning=FALSE}
hic.table <- hic_loess(dplfc1_2, Plot = TRUE)
hic.table <- hic_compare(hic.table, Plot = TRUE)
```


## unadjusted 

```{r}
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.value)
```

