---
title: "ranking_ROC"
author: "John Stansfield"
date: "December 3, 2017"
output: html_document
---

# ROC curves on ranks

```{r}
# SET UP PARAMETERS
N = 300
FOLD.CHANGE = 4
```


```{r}
library(readr)
library(data.table)
library(HiCcompare)
library(dplyr)
library(pROC)
```


```{r}
# function to calculate TP, FP, TN, FN
pre_roc <- function(hic.table, i.range, j.range) {
  # hic.table must of diff_indicator column with 1 for difference, 0 for no difference
  # get true.diffs
  true.diffs <- data.table(i = c(i.range, j.range), j = c(j.range, i.range))
  true.diffs <- left_join(true.diffs, sim, by = c(i = "start1", j = "start2"))
  # remove duplicated rows
  true.diffs <- true.diffs[!duplicated(true.diffs), ]
  true.diffs <- as.data.table(na.omit(true.diffs))
  # calculate TP, FP, FN, TN
  true.pos <- sum(true.diffs$diff_indicator == 1)
  false.pos <- sum(hic.table$diff_indicator == 1, na.rm = TRUE) - true.pos
  false.neg <- nrow(true.diffs) - true.pos
  true.neg <- nrow(hic.table) - true.pos - false.pos - false.neg
  result <- c('TP' = true.pos, 'FP' = false.pos, 'TN' = true.neg, 'FN' = false.neg)
  # make vectors to feed into ROC packages vector of p-value decision
  temp.true.diffs <- true.diffs[, `:=`(truth, 1)]
  temp.true.diffs <- temp.true.diffs[, c("i", "j", "truth"), with = FALSE]
  truth <- left_join(hic.table, temp.true.diffs, by = c(start1 = "i", start2 = "j"))
  truth$truth[is.na(truth$truth)] <- 0
  truth <- truth$truth
  result <- list(values = result, truth = truth)
  return(result)
}
```


```{r}
# simulate matrices
i.range = sample(1:150, replace=TRUE, size = N)
j.range = sample(1:150, replace=TRUE, size = N)
sim <- hic_sim_matrix(nrow = 150, fold.change = FOLD.CHANGE, i.range = i.range, j.range = j.range)

# MD.plot2(sim$M, sim$D)

# So general plan should be to simulate matrices, run thru hic_diff
# then make indicator column for difference
# plug hic.table with indicator into function to calculate TP, FP, TN, FN as done in hic_simulate

# normalize and rank
sim <- hic_loess(sim, Plot = FALSE)
sim <- hic_diff(sim, Plot = FALSE)

# ROC for mean(M, A, diff)
# set up
alpha <- 0.05
idx <- 1:(nrow(sim) * alpha)

sim <- sim[order(rnkMean),]
diffs <- rep(0, nrow(sim))
diffs[idx] <- 1
sim[, diff_indicator := diffs]

mean_A_M_diff <- pre_roc(sim, i.range, j.range)

sim[, truth := mean_A_M_diff$truth]
sim[truth == 1,]

roc_mean_A_M_diff <- roc(response = sim$truth, predictor = sim$rnkMean)

# for max(M, A, diff)
sim <- sim[order(rnkMax),]
diffs <- rep(0, nrow(sim))
diffs[idx] <- 1
sim[, diff_indicator := diffs]
roc_max_A_M_diff <- roc(response = sim$truth, predictor = sim$rnkMax)

# for rnkM only
sim <- sim[order(rnkM),]
diffs <- rep(0, nrow(sim))
diffs[idx] <- 1
sim[, diff_indicator := diffs]
roc_rnkM <- roc(response = sim$truth, predictor = sim$rnkM)

# for rnkDiff only
sim <- sim[order(rnkDiff),]
diffs <- rep(0, nrow(sim))
diffs[idx] <- 1
sim[, diff_indicator := diffs]
roc_rnkDiff <- roc(response = sim$truth, predictor = sim$rnkDiff)

# for mean(M, A) with D weighting
mean_rank <- sim %>% dplyr::select(rnkM, rnkA) %>% as.matrix() %>% apply(., 1, mean)
sim[, rnkMean := mean_rank]
# create weight for distance
dist_weight <- 1+((sim$D + 1)/max(sim$D + 1))
sim[, rnkMean := dist_weight * rnkMean]
sim <- sim[order(rnkMean),]
roc_D_weight <- roc(response = sim$truth, predictor = sim$rnkMean)

# for rnkM_D only
sim <- sim[order(rnkM_D),]
diffs <- rep(0, nrow(sim))
diffs[idx] <- 1
sim[, diff_indicator := diffs]
roc_rnkM_D <- roc(response = sim$truth, predictor = sim$rnkM_D)

# for mean(M, A, Diff) with D weighting
mean_rank <- sim %>% dplyr::select(rnkM, rnkA, rnkDiff) %>% as.matrix() %>% apply(., 1, mean)
sim[, rnkMean := mean_rank]
# create weight for distance
dist_weight <- 1+((sim$D + 1)/max(sim$D + 1))
sim[, rnkMean := dist_weight * rnkMean]
sim <- sim[order(rnkMean),]
roc_D_weight2 <- roc(response = sim$truth, predictor = sim$rnkMean)

# plots
plot.colors <- c('black', 'red', 'blue', 'green', 'yellow', 'orange', 'purple')
plot(roc_mean_A_M_diff, main = paste0('Fold change = ', FOLD.CHANGE))
plot(roc_max_A_M_diff, col = plot.colors[2], add = TRUE)
plot(roc_rnkM, col = plot.colors[3], add = TRUE)
plot(roc_rnkDiff, col = plot.colors[4], add = TRUE)
plot(roc_D_weight, col = plot.colors[5], add = TRUE) # mean (M, A) w/ Dist weight
plot(roc_D_weight2, col = plot.colors[6], add = TRUE) # mean(M, A, Diff) w/ dist weight
plot(roc_rnkM_D, col = plot.colors[7], add = TRUE)
legend('bottomright', inset = 0, legend = c('mean(M, A, Diff)', 'max(M, A, Diff)', 'rnkM', 'rnkDiff', 'mean(M, A)*D_weight', 'mean(M, A, diff)*D_weight',
                                            'rnkM_D'), title = 'Method', fill = plot.colors, horiz = F)
```





