---
title: "smyth_goldstandard"
author: "John Stansfield"
date: "December 31, 2017"
output:
  pdf_document: default
  html_document: default
---

# set up

```{r}
library(HiCcompare)
library(data.table)
library(InteractionSet)
library(MDmisc)
library(ggplot2)
library(gridExtra)
library(pROC)
```

```{r}
options(stringsAsFactors = FALSE)
```

```{r}
dataframe2interactionset <- function(df) {
  df <- as.data.frame(df)
  set1 <- GRanges(df$chr1, IRanges(start = df$start1, end = df$end1))
  set2 <- GRanges(df$chr2, IRanges(start = df$start2, end = df$end2))
  gi <- GInteractions(set1, set2)
  if (ncol(df) > 6) {
    S4Vectors::values(gi) <- cbind(S4Vectors::values(gi), df[, 7:ncol(df)])
  }
  return(gi)
}
```


## read in lib1 data
```{r}
# core_path <- "C:/VM_Shared/DNA_int_analysis/rickman/rickman_lib1/"
# man_path <- "C:/VM_Shared/DNA_int_analysis/manuscript/prostate_analysis/"

core_path <- "D:/3D_DNA/rickman/rickman_lib1/"
man_path <- "D:/3D_DNA/manuscript/prostate_analysis/"

chrs <- paste0('chr', 1:22)
chrs <- c(chrs, 'chrX')

# read in data for 1 mb
ERG_lib1 <- list()
GFP_lib1 <- list()
for(i in 1:22) {
  ERG_lib1[[i]] <- read.table(paste0(core_path, 'ERG_lib1_chr', i, '.1mb.txt'), header = FALSE)
  GFP_lib1[[i]] <- read.table(paste0(core_path, 'GFP_lib1_chr', i, '.1mb.txt'), header = FALSE)
}
ERG_lib1[[23]] <- read.table(paste0(core_path, 'ERG_lib1_chr', 'X', '.1mb.txt'), header = FALSE)
GFP_lib1[[23]] <- read.table(paste0(core_path, 'GFP_lib1_chr', 'X', '.1mb.txt'), header = FALSE)

```

## Run hiccompare on data
```{r}
lib1_tables <- mapply(create.hic.table, ERG_lib1, GFP_lib1, chrs, SIMPLIFY = FALSE, MoreArgs = list(scale = FALSE, include.zeros = FALSE)) #,
                                                                                                    # exclude.regions = exclude, 
                                                                                                    # exclude.overlap = 0.2))


lib1_tables <- total_sum(lib1_tables)
```

```{r}
# pdf(file = paste0(man_path, 'new_data.pdf'))
lib1_tables <- hic_loess(lib1_tables, Plot = FALSE, span = NA)
# dev.off()

# pdf(file = paste0(man_path, 'new_data_diff.pdf'))
# lib1_tables <- hic_diff(lib1_tables, Plot = TRUE, diff.thresh = NA, iterations = 1000)
# dev.off()

lib1_tables <- hic_compare(lib1_tables, Plot = FALSE, adjust_dist = TRUE, A.quantile = 0.05, p.method = 'holm')
```


## Read in smyth data

```{r}
# set up their data for overlap analysis
# core_path <- "C:/VM_Shared/DNA_int_analysis/prostate_data/"
core_path <- "D:/3D_DNA/prostate_data/"
library(readr)
their.results <- read_tsv(paste0(core_path, 'results.tsv'))
# their.results <- subset(their.results, FDR < 0.05)
# they used the lower triangle of the matrix for most pairs of regions while we only use upper triangle. need to convert to upper triangle for overlap to work
new_start1 <- ifelse(their.results$anchor.start >= their.results$target.start, their.results$target.start, their.results$anchor.start)
new_end1 <- ifelse(their.results$anchor.end >= their.results$target.end, their.results$target.end, their.results$anchor.end)
new_start2 <- ifelse(their.results$anchor.start >= their.results$target.start, their.results$anchor.start, their.results$target.start)
new_end2 <- ifelse(their.results$anchor.end >= their.results$target.end, their.results$anchor.end, their.results$target.end)
new.their.results <- data.frame(anchor = their.results$anchor, anchor.start = new_start1, anchor.end = new_end1, 
                                target = their.results$target, target.start = new_start2, target.end = new_end2)
new.their.results <- cbind(new.their.results, their.results[, 7:11])
their.results <- new.their.results
s1 <- GRanges(their.results$anchor, IRanges(start = their.results$anchor.start, end = their.results$anchor.end))
s2 <- GRanges(their.results$target, IRanges(start = their.results$target.start, end = their.results$target.end))
smyth.gi <- GInteractions(s1, s2)
meta <- cbind(their.results$logFC, their.results$logCPM, their.results$F, their.results$PValue, their.results$FDR)
meta <- as.data.frame(meta)
colnames(meta) <- c('logFC', 'logCPM', 'F', 'PValue', 'FDR')
S4Vectors::values(smyth.gi) <- cbind(S4Vectors::values(smyth.gi), meta)
```

# overlap significant smyth regions with our regions

```{r}
# combine out results into single object & convert to interaction set
ours <- rbindlist(lib1_tables)
ours <- dataframe2interactionset(ours)

# get significant smyth interactions
smyth.sig <- smyth.gi[smyth.gi$FDR < 0.05,]
smyth.sig <- sort(smyth.sig)

# get overlaps
olaps <- InteractionSet::findOverlaps(smyth.sig, ours, use.region = 'same', minoverlap = 10000)
# make truth vector
truth <- rep(0, length(ours))
truth[unique(olaps@to)] <- 1
```


# ROC 

```{r}
pval_roc <- roc(response = truth, predictor = ours@elementMetadata$p.value)
adjpval_roc <- roc(response = truth, predictor = ours@elementMetadata$p.adj)


plot(pval_roc)
plot(adjpval_roc, add = TRUE, col = 'red')
```


# look at how smyth corresponds to our results

```{r}
sum(truth == 1)
sum(truth == 1 & ours@elementMetadata$p.adj < 0.05)
sum(truth == 1 & ours@elementMetadata$p.value < 0.05)


```

smyth significant regions and our significant regions barely overlap.

