---
title: "test_fisher"
author: "John Stansfield"
date: "December 14, 2017"
output:
  pdf_document: default
  html_document: default
---




```{r, message=F, warning=F}
library(readr)
library(data.table)
library(HiCcompare)
library(dplyr)
library(pROC)
```

```{r, message = FALSE, warning=FALSE, results='hide', cache=FALSE, echo = FALSE}
# Set up
#####
centromeres <- read.table("D:/brain/data/hg38_centromeres.bed")

# for dplfc 1 (dplfc folder)
dplfc_1_mat <- read_tsv("D:/brain/data/all_resolutions/dplfc_1000000.matrix", col_names = FALSE) %>% as.data.table()
dplfc_1_bed <- read_tsv("D:/brain/data/all_resolutions/dplfc_1000000_abs.bed", col_names = FALSE) %>% as.data.table()

# for dplfc 2 (dplfc folder)
dplfc_2_mat <- read_tsv("D:/brain/data/all_resolutions/dplfc_upseq_1000000.matrix", col_names = FALSE) %>% as.data.table()
dplfc_2_bed <- read_tsv("D:/brain/data/all_resolutions/dplfc_upseq_1000000_abs.bed", col_names = FALSE) %>% as.data.table()


dplfc_1 <- hicpro2bedpe(dplfc_1_mat, dplfc_1_bed)$cis[-c(23,25)] # remove chrM and chrY
dplfc_2 <- hicpro2bedpe(dplfc_2_mat, dplfc_1_bed)$cis[-c(23,25)] # remove chrM and chrY

dplfc1_2 <- mapply(create.hic.table, dplfc_1[1:3], dplfc_2[1:3], MoreArgs = list(exclude.regions = centromeres, exclude.overlap = 0,
                                                                       scale = TRUE), SIMPLIFY = FALSE)

```


```{r}
make_changes <- function(hic.table, N = 300, FC = 2, quant = 0.25) {
  # introduce changes
  changes <- sample(1:nrow(hic.table), size = N)
  whichIF = ifelse(hic.table[changes, ]$M < 0, -1, 1)
  newIF1 = FC^whichIF * hic.table[changes,]$IF2
  newIF1 = (round(newIF1))
  newIF1[newIF1 < 0.01] <- 1
  hic.table[changes,]$IF1 = newIF1
  hic.table = hic.table[, M := log2(IF2/IF1)]
  
  # make truth vector
  truth <- rep(0, nrow(hic.table))
  truth[changes] <- 1
  hic.table[, truth := truth]
  
  # normalize
  hic.table <- hic_loess(hic.table, Plot = FALSE)
  hic.table <- hic_diff(hic.table, Plot = TRUE)
  
  
  # roc_result <- roc(response = result$truth, predictor = result$p.val)
  # return(roc_result)
  return(hic.table)
}
```


```{r}
# pvalue adjustment -  FDR by distance
fdr_adjust <- function(hic.table) {
   # split table up for each distance
  temp_list <- S4Vectors::split(hic.table, hic.table$D)
  # combined top 15% of distances into single data.table
  all_dist <- sort(unique(hic.table$D))
  dist_85 <- ceiling(0.85 * length(all_dist))
  temp_list2 <- temp_list[1:dist_85]
  temp_list2[[dist_85+1]] <- data.table::rbindlist(temp_list[(dist_85+1):length(temp_list)])
  temp_list <- temp_list2
  rm("temp_list2")
  # rank M by distance
  temp_list <- lapply(temp_list, function(x) {
    x[, p.adj := p.adjust(p.val, method = 'fdr')]
    return(x)
  })
  # recombine into one table
  hic.table <- rbindlist(temp_list)
  MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj) 
  return(hic.table)
}
```


```{r}
calc_stats1 <- function(hic.table) {
  TP <- sum(hic.table$truth == 1 & hic.table$p.val < 0.05) 
  TN <- sum(hic.table$truth == 0 & hic.table$p.val > 0.05) 
  FP <- sum(hic.table$truth == 0 & hic.table$p.val < 0.05)
  FN <- sum(hic.table$truth == 1 & hic.table$p.val > 0.05)
  TPR <- TP / (TP + FN)
  TNR <- TN / (TN + FP)
  PPV <- TP / (TP + FP)
  NPV <- TN / (TN + FN)
  FPR <- FP / (FP + TN)
  FNR <- FN / (TP + FN)
  FDR <- FP / (TP + FP)
  ACC <- (TP + TN) / (TP + FP + FN + TN)
  res <- data.frame(TPR = TPR, TNR = TNR, PPV = PPV, NPV = NPV, FPR = FPR, FNR = FNR, FDR = FDR, ACC = ACC)
  knitr::kable(res)
}


calc_stats <- function(hic.table) {
  TP <- sum(hic.table$truth == 1 & hic.table$p.adj < 0.05) 
  TN <- sum(hic.table$truth == 0 & hic.table$p.adj > 0.05) 
  FP <- sum(hic.table$truth == 0 & hic.table$p.adj < 0.05)
  FN <- sum(hic.table$truth == 1 & hic.table$p.adj > 0.05)
  TPR <- TP / (TP + FN)
  TNR <- TN / (TN + FP)
  PPV <- TP / (TP + FP)
  NPV <- TN / (TN + FN)
  FPR <- FP / (FP + TN)
  FNR <- FN / (TP + FN)
  FDR <- FP / (TP + FP)
  ACC <- (TP + TN) / (TP + FP + FN + TN)
  res <- data.frame(TPR = TPR, TNR = TNR, PPV = PPV, NPV = NPV, FPR = FPR, FNR = FNR, FDR = FDR, ACC = ACC)
  knitr::kable(res)
}
```



# Test fisher test

## N = 300 FC = 1.5

```{r}
hic.table <- dplfc1_2[[1]]
backup.table <- hic.table


hic.table <- make_changes(hic.table, N = 300, FC = 1.5, quant = 0.25)
## True positive rate:
calc_stats1(hic.table)

# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
calc_stats(hic.table)



# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)
```


## N = 300 FC = 2

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 2, quant = 0.25)
## True positive rate:
calc_stats1(hic.table)

# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
## True positive rate:
calc_stats(hic.table)


# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)
```

## N = 300 FC = 3

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 3, quant = 0.25)
## True positive rate:
calc_stats1(hic.table)

# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
## True positive rate:
calc_stats(hic.table)


# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)
```

## N = 300 FC = 4

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 4, quant = 0.25)
## True positive rate:
calc_stats1(hic.table)


# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
## True positive rate:
calc_stats(hic.table)


# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)

```

## N = 50 FC = 3

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 50, FC = 4, quant = 0.25)
calc_stats1(hic.table)

# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
## True positive rate:
calc_stats(hic.table)



# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)
```


## N = 50 FC = 4

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 50, FC = 4, quant = 0.25)
## True positive rate:
calc_stats1(hic.table)

# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
## True positive rate:
calc_stats(hic.table)


# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)
```

## No changes

```{r}
hic.table <- backup.table
hic.table <- hic_loess(hic.table, Plot = FALSE)
hic.table <- hic_diff(hic.table, Plot = TRUE)
## False positives
calc_stats1(hic.table)

# FDR on full vector
hic.table[, p.adj := p.adjust(p.val, method = 'fdr')]
MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj)
## False positives
calc_stats(hic.table)



# FDR by distance
hic.table <- fdr_adjust(hic.table)
calc_stats(hic.table)
```

