---
title: "zscore_Athreshold"
author: "John Stansfield"
date: "December 11, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r, message=F, warning=F}
library(readr)
library(data.table)
library(HiCcompare)
library(dplyr)
library(pROC)
```

```{r, message = FALSE, warning=FALSE, results='hide', cache=FALSE, echo = FALSE}
# Set up
#####
centromeres <- read.table("D:/brain/data/hg38_centromeres.bed")

# for dplfc 1 (dplfc folder)
dplfc_1_mat <- read_tsv("D:/brain/data/all_resolutions/dplfc_1000000.matrix", col_names = FALSE) %>% as.data.table()
dplfc_1_bed <- read_tsv("D:/brain/data/all_resolutions/dplfc_1000000_abs.bed", col_names = FALSE) %>% as.data.table()

# for dplfc 2 (dplfc folder)
dplfc_2_mat <- read_tsv("D:/brain/data/all_resolutions/dplfc_upseq_1000000.matrix", col_names = FALSE) %>% as.data.table()
dplfc_2_bed <- read_tsv("D:/brain/data/all_resolutions/dplfc_upseq_1000000_abs.bed", col_names = FALSE) %>% as.data.table()


dplfc_1 <- hicpro2bedpe(dplfc_1_mat, dplfc_1_bed)$cis[-c(23,25)] # remove chrM and chrY
dplfc_2 <- hicpro2bedpe(dplfc_2_mat, dplfc_1_bed)$cis[-c(23,25)] # remove chrM and chrY

dplfc1_2 <- mapply(create.hic.table, dplfc_1[1:3], dplfc_2[1:3], MoreArgs = list(exclude.regions = centromeres, exclude.overlap = 0,
                                                                       scale = TRUE), SIMPLIFY = FALSE)

```


```{r}
# version where z scores calculated first then z scores with A < thresh set to 0
.calc_z <- function(hic.table, quant = 0.25) {
  threshold <- quantile((hic.table$A), quant, na.rm = TRUE)
  Z <- (hic.table$adj.M - mean(hic.table$adj.M)) / sd(hic.table$adj.M)
  # set z-scores where A < threshold to 0
  Z[hic.table$A < threshold] <- 0
  hic.table[, Z := Z]
  hic.table[, p.val := 2*pnorm(abs(Z), lower.tail = FALSE)]
  # hic.table[, p.adj := p.adjust(p.val, method = 'holm')]
  MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.val) 
  # MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj) 
  return(hic.table)
}
```


```{r}
# version where M values with A < 0 removed before z score calculations
.calc_z2 <- function(hic.table, quant = 0.25) {
  threshold <- quantile((hic.table$A), quant, na.rm = TRUE)
  new_M <- hic.table$adj.M
  new_M[hic.table$A < threshold] <- NA
  Z <- (new_M - mean(new_M, na.rm = TRUE)) / sd(new_M, na.rm = TRUE)
  # set z-scores where A < threshold to 0
  # Z[hic.table$A < threshold] <- 0
  hic.table[, Z := Z]
  hic.table[, p.val := 2*pnorm(abs(Z), lower.tail = FALSE)]
  # hic.table[, p.adj := p.adjust(p.val, method = 'holm')]
  MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.val) 
  # MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj) 
  return(hic.table)
}
```


```{r}
# pvalue adjustment
holm_adjust <- function(hic.table) {
   # split table up for each distance
  temp_list <- S4Vectors::split(hic.table, hic.table$D)
  # combined top 15% of distances into single data.table
  all_dist <- sort(unique(hic.table$D))
  dist_85 <- ceiling(0.85 * length(all_dist))
  temp_list2 <- temp_list[1:dist_85]
  temp_list2[[dist_85+1]] <- data.table::rbindlist(temp_list[(dist_85+1):length(temp_list)])
  temp_list <- temp_list2
  rm("temp_list2")
  # rank M by distance
  temp_list <- lapply(temp_list, function(x) {
    x[, p.adj := p.adjust(p.val, method = 'holm')]
    return(x)
  })
  # recombine into one table
  hic.table <- rbindlist(temp_list)
  MD.plot2(hic.table$adj.M, hic.table$D, hic.table$p.adj) 
  return(hic.table)
}
```



```{r}
make_roc <- function(hic.table, N = 300, FC = 2, quant = 0.25) {
  # introduce changes
  changes <- sample(1:nrow(hic.table), size = N)
  whichIF = ifelse(hic.table[changes, ]$M < 0, -1, 1)
  newIF1 = FC^whichIF * hic.table[changes,]$IF2
  newIF1 = (round(newIF1))
  newIF1[newIF1 < 0.01] <- 1
  hic.table[changes,]$IF1 = newIF1
  hic.table = hic.table[, M := log2(IF2/IF1)]
  
  # make truth vector
  truth <- rep(0, nrow(hic.table))
  truth[changes] <- 1
  hic.table[, truth := truth]
  
  # normalize
  hic.table <- hic_loess(hic.table, Plot = FALSE)
  hic.table <- hic_diff(hic.table, Plot = FALSE)
  
  result <- .calc_z2(hic.table, quant = quant)
  roc_result <- roc(response = result$truth, predictor = result$p.val)
  return(roc_result)
}
```


# build ROC

# Varying fold change

## Fold change = 1.5
```{r, warning=FALSE, message=FALSE}
hic.table <- dplfc1_2[[1]]
backup.table <- hic.table

quant5 <- make_roc(hic.table, N = 300, FC = 1.5, quant = 0.05)
rm("hic.table")
hic.table <- backup.table
quant10 <- make_roc(hic.table, N = 300, FC = 1.5, quant = 0.1)
rm("hic.table")
hic.table <- backup.table
quant20 <- make_roc(hic.table, N = 300, FC = 1.5, quant = 0.2)
rm("hic.table")
hic.table <- backup.table
quant25 <- make_roc(hic.table, N = 300, FC = 1.5, quant = 0.25)
rm("hic.table")
hic.table <- backup.table
quant0 <- make_roc(hic.table, N = 300, FC = 1.5, quant = 0)
```

```{r}
plot.colors <- c('black', 'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'lightblue')
plot(quant5, main = paste0('Fold change = ', 1.5))
plot(quant10, add = TRUE, col = plot.colors[2])
plot(quant20, add = TRUE, col = plot.colors[3])
plot(quant25, add = TRUE, col = plot.colors[4])
plot(quant0, add = TRUE, col = plot.colors[5])
legend('bottomright', inset = 0, legend = c('5%', '10%', '20%', '25%', '0%'), title = 'Quantile', fill = plot.colors[1:5], horiz = F)
```



## Fold change = 2
```{r, warning=FALSE, message=FALSE}
rm("hic.table")
hic.table <- dplfc1_2[[1]]
backup.table <- hic.table

quant5 <- make_roc(hic.table, N = 300, FC = 2, quant = 0.05)
rm("hic.table")
hic.table <- backup.table
quant10 <- make_roc(hic.table, N = 300, FC = 2, quant = 0.1)
rm("hic.table")
hic.table <- backup.table
quant20 <- make_roc(hic.table, N = 300, FC = 2, quant = 0.2)
rm("hic.table")
hic.table <- backup.table
quant25 <- make_roc(hic.table, N = 300, FC = 2, quant = 0.25)
rm("hic.table")
hic.table <- backup.table
quant0 <- make_roc(hic.table, N = 300, FC = 2, quant = 0)
```

```{r}
plot.colors <- c('black', 'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'lightblue')
plot(quant5, main = paste0('Fold change = ', 2))
plot(quant10, add = TRUE, col = plot.colors[2])
plot(quant20, add = TRUE, col = plot.colors[3])
plot(quant25, add = TRUE, col = plot.colors[4])
plot(quant0, add = TRUE, col = plot.colors[5])
legend('bottomright', inset = 0, legend = c('5%', '10%', '20%', '25%', '0%'), title = 'Quantile', fill = plot.colors[1:5], horiz = F)
```



## Fold change = 4
```{r, warning=FALSE, message=FALSE}
rm("hic.table")
hic.table <- dplfc1_2[[1]]
backup.table <- hic.table

quant5 <- make_roc(hic.table, N = 300, FC = 4, quant = 0.05)
rm("hic.table")
hic.table <- backup.table
quant10 <- make_roc(hic.table, N = 300, FC = 4, quant = 0.1)
rm("hic.table")
hic.table <- backup.table
quant20 <- make_roc(hic.table, N = 300, FC = 4, quant = 0.2)
rm("hic.table")
hic.table <- backup.table
quant25 <- make_roc(hic.table, N = 300, FC = 4, quant = 0.25)
rm("hic.table")
hic.table <- backup.table
quant0 <- make_roc(hic.table, N = 300, FC = 4, quant = 0)
```

```{r}
plot.colors <- c('black', 'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'lightblue')
plot(quant5, main = paste0('Fold change = ', 4))
plot(quant10, add = TRUE, col = plot.colors[2])
plot(quant20, add = TRUE, col = plot.colors[3])
plot(quant25, add = TRUE, col = plot.colors[4])
plot(quant0, add = TRUE, col = plot.colors[5])
legend('bottomright', inset = 0, legend = c('5%', '10%', '20%', '25%', '0%'), title = 'Quantile', fill = plot.colors[1:5], horiz = F)
```




# Varying number differences

## 50 changes 3 FC
```{r, warning=FALSE, message=FALSE}
rm("hic.table")
hic.table <- dplfc1_2[[1]]
backup.table <- hic.table

quant5 <- make_roc(hic.table, N = 50, FC = 3, quant = 0.05)
rm("hic.table")
hic.table <- backup.table
quant10 <- make_roc(hic.table, N = 50, FC = 3, quant = 0.1)
rm("hic.table")
hic.table <- backup.table
quant20 <- make_roc(hic.table, N = 50, FC = 3, quant = 0.2)
rm("hic.table")
hic.table <- backup.table
quant25 <- make_roc(hic.table, N = 50, FC = 3, quant = 0.25)
rm("hic.table")
hic.table <- backup.table
quant0 <- make_roc(hic.table, N = 50, FC = 3, quant = 0)
```

```{r}
plot.colors <- c('black', 'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'lightblue')
plot(quant5, main = paste0('Fold change = ', 3))
plot(quant10, add = TRUE, col = plot.colors[2])
plot(quant20, add = TRUE, col = plot.colors[3])
plot(quant25, add = TRUE, col = plot.colors[4])
plot(quant0, add = TRUE, col = plot.colors[5])
legend('bottomright', inset = 0, legend = c('5%', '10%', '20%', '25%', '0%'), title = 'Quantile', fill = plot.colors[1:5], horiz = F)
```


## 500 changes 2 FC
```{r, warning=FALSE, message=FALSE}
rm("hic.table")
hic.table <- dplfc1_2[[1]]
backup.table <- hic.table

quant5 <- make_roc(hic.table, N = 500, FC = 2, quant = 0.05)
rm("hic.table")
hic.table <- backup.table
quant10 <- make_roc(hic.table, N = 500, FC = 2, quant = 0.1)
rm("hic.table")
hic.table <- backup.table
quant20 <- make_roc(hic.table, N = 500, FC = 2, quant = 0.2)
rm("hic.table")
hic.table <- backup.table
quant25 <- make_roc(hic.table, N = 500, FC = 2, quant = 0.25)
rm("hic.table")
hic.table <- backup.table
quant0 <- make_roc(hic.table, N = 500, FC = 2, quant = 0)
```

```{r}
plot.colors <- c('black', 'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'lightblue')
plot(quant5, main = paste0('Fold change = ', 2))
plot(quant10, add = TRUE, col = plot.colors[2])
plot(quant20, add = TRUE, col = plot.colors[3])
plot(quant25, add = TRUE, col = plot.colors[4])
plot(quant0, add = TRUE, col = plot.colors[5])
legend('bottomright', inset = 0, legend = c('5%', '10%', '20%', '25%', '0%'), title = 'Quantile', fill = plot.colors[1:5], horiz = F)
```


# Test holm p-value adjustment by distance

```{r}
make_changes <- function(hic.table, N = 300, FC = 2, quant = 0.25) {
  # introduce changes
  changes <- sample(1:nrow(hic.table), size = N)
  whichIF = ifelse(hic.table[changes, ]$M < 0, -1, 1)
  newIF1 = FC^whichIF * hic.table[changes,]$IF2
  newIF1 = (round(newIF1))
  newIF1[newIF1 < 0.01] <- 1
  hic.table[changes,]$IF1 = newIF1
  hic.table = hic.table[, M := log2(IF2/IF1)]
  
  # make truth vector
  truth <- rep(0, nrow(hic.table))
  truth[changes] <- 1
  hic.table[, truth := truth]
  
  # normalize
  hic.table <- hic_loess(hic.table, Plot = FALSE)
  hic.table <- hic_diff(hic.table, Plot = FALSE)
  
  result <- .calc_z2(hic.table, quant = quant)
  # roc_result <- roc(response = result$truth, predictor = result$p.val)
  # return(roc_result)
  return(result)
}
```





## N = 300 FC = 1.5

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 1.5, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```


## N = 300 FC = 2

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 2, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```

## N = 300 FC = 3

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 3, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```

## N = 300 FC = 4

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 300, FC = 4, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```

## N = 50 FC = 3

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 50, FC = 4, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```


## N = 50 FC = 4

```{r}
hic.table <- backup.table

hic.table <- make_changes(hic.table, N = 50, FC = 4, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```

## No changes

```{r}
hic.table <- backup.table
hic.table <- hic_loess(hic.table, Plot = FALSE)
hic.table <- hic_diff(hic.table, Plot = FALSE)
hic.table <- .calc_z(hic.table, quant = 0.25)
hic.table <- holm_adjust(hic.table)
```

